### ISSUE TITLE
Name conflict?

### ISSUE THREAD

**Issue by probonopd** [samjavner/silver-bullet-cookbook#3]
The project could benefit from a description. When I search for "pepperzip", I basically only find instructions on how to _remove_ a spyware with the same name.

http://lmgtfy.com/?q=pepperzip

Perhaps you may want to clarify this.

**Comment by samjavner** [comment]
Yes, this could benefit from a description! And thanks for reminding me about the spyware.

I'll change the name to avoid the naming issue and add a minimal readme.
